### ISSUE TITLE
zaprojektowanie strony z kodem aktywacyjnym i reset hasła

### ISSUE THREAD

**Issue by maktowon** [aniafaf/IOproject#24]

**Comment by LaMavia** [comment]
Dodałam ogólny layout w #31 . Zmieniłam trochę rozmiar drop-shadowa i border-radius, gdyż wydawały mi się dość spore, więc daj znać, co sądzisz. Sam contents będzie można łatwo dodać jako `children`

![Image](https://user-images.githubusercontent.com/28303367/227680356-5514e429-c500-4083-9576-4e6e727ce55e.png)

**Comment by LaMavia** [comment]
Pełen przykład jest w #32

**Comment by aniafaf** [comment]
zwiększyłabym odrobinę shadow, żeby bardziej wysunąć panel z backgroundu, a tak to spoko:)

**Comment by LaMavia** [comment]
Tyle starczy? Osobiście bardziej przepadam za minimalnymi shadowami, ale to bardzo subiektywne

![Image](https://user-images.githubusercontent.com/28303367/227776849-861272cc-e060-48ff-8122-28a457b53d3a.png)
