### ISSUE TITLE
diagram bazy danych dla uzytkownika

### ISSUE THREAD

**Issue by aniafaf** [aniafaf/IOproject#3]

**Comment by maktowon** [comment]
![accountApp-2023-03-25_17-12](https://user-images.githubusercontent.com/108530595/227728946-f3bb76b4-d12c-45ce-bba9-70299f9992fb.png)

**Comment by LaMavia** [comment]
Czy moglibyśmy użyć par jako PK w `UserGroup { (group_id, user_id) PK, group_id FK, user_id FK }` i `Debtors { (user_id, payment_id) PK, user_id FK, payment_id FK }`? te `id, linking_id` są zbędne według mnie, no chyba że ORM ma problem z tuplowymi kluczami

**Comment by maktowon** [comment]
O ile dobrze zrozumiałem przy poprzednim projekcie, to baza danych tworzyła się sama na podstawie klas z Django. Teraz znalazłem, że jest na to gotowe rozwiązanie w Django: ManyToManyField (https://docs.djangoproject.com/en/4.1/topics/db/examples/many_to_many/) więc może w ogóle te tabele nie będą potrzebne
