### ISSUE TITLE
Ustawienie CI/CD

### ISSUE THREAD

**Issue by aniafaf** [aniafaf/IOproject#5]

**Comment by LaMavia** [comment]
Ustawiłam CI dla clienta w #30 . Czeka jeszcze CI dla serwera i [CD](https://github.com/marketplace/actions/deploy-to-heroku)

**Comment by LaMavia** [comment]
Popracowałam nad dodaniem builda frontu do buildpacka heroku ([repo](https://github.com/LaMavia/heroku-buildpack-io)) i chodzi testowo na [https://io-project.herokuapp.com/#/login](https://io-project.herokuapp.com/#/login)

**Comment by LaMavia** [comment]
Poczekam jeszcze na permy dla botów i spróbuję zmerge'ować do maina

**Comment by LaMavia** [comment]
Koniec w #47
